### ISSUE TITLE
The zksolc binary at path zksolc is corrupted. Please delete it and try again.

### ISSUE THREAD

**Issue by chenlaoyao0523** [matter-labs/zksolc-bin#11]
yarn run v1.22.19
warning package.json: No license field
$ /root/dev/chainpray/node_modules/.bin/hardhat compile
Error in plugin @matterlabs/hardhat-zksync-solc: The zksolc binary at path zksolc is corrupted. Please delete it and try again.

ZkSyncSolcPluginError: The zksolc binary at path zksolc is corrupted. Please delete it and try again.
    at ZksolcCompilerDownloader._verifyCompiler (/root/dev/chainpray/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/downloader.ts:202:19)
    at ZksolcCompilerDownloader.isCompilerDownloaded (/root/dev/chainpray/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/downloader.ts:100:24)
    at /root/dev/chainpray/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:83:59
    at async OverriddenTaskDefinition._action (/root/dev/chainpray/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:76:5)
    at async Environment._runTaskDefinition (/root/dev/chainpray/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/root/dev/chainpray/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/root/dev/chainpray/node_modules/hardhat/src/builtin-tasks/compile.ts:1329:9)
    at async Environment._runTaskDefinition (/root/dev/chainpray/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/root/dev/chainpray/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/root/dev/chainpray/node_modules/hardhat/src/builtin-tasks/compile.ts:1432:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nourhelmi** [comment]
I'm also having this issue, there doesn't seem to be a straight forward solution... trying the downloader also isn't working either:
```
Compiling 55 Solidity files
  hardhat:core:hre Running task compile:solidity:solc:run +0ms
  hardhat:core:analytics Hit for task sent successfully +252ms
An unexpected error occurred:

Error: Command failed: /Users/xxx/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.3.13 --standard-json    --solc /Users/xxx/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.17+commit.8df45f5f
invalid value: string "200", expected a character at line 1 column 254580

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:709:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/xxx/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.3.13 --standard-json    --solc /Users/xxx/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.17+commit.8df45f5f'
}
```

**Comment by nourhelmi** [comment]
The issue seems to stem from a conflict with zksync hardhat plugins and `hardhat-toolbox` package. Removing the latter fixed the issue

**Comment by hedgar2017** [comment]
The binaries have been tested and are fine.
Please report further issues in the hardhat repos.
